### ISSUE TITLE
Update fortran code calls to remove deprecated IO

### ISSUE THREAD

**Issue by durack1** [PCMDI/amipbcs#14]
There is a need to modernize the process to generate these datasets, removing the dependence on the `EzGet`, `lats` and `libdrs` libraries. @pochedls has managed to achieve this using `f2py` and has a working example that requires validation

@taylor13 ping

**Comment by doutriaux1** [comment]
@durack1 I agree, ezget is now cdms2/regrid2, lats can be replaced by cdms or cmor. The "pure" fortran can be indeed converted with numpy, but could very well be rewritten in pure python, maybe even improved via dask if speed is an issue.

**Comment by durack1** [comment]
@pochedls code added to [issue14_durack1_UpdateFortranCodeCalls](https://github.com/PCMDI/amipbcs/tree/issue14_durack1_UpdateFortranCodeCalls)

@doutriaux1 @pochedls has pulled out the guts of the `mkhurrell1.f` code and dropped it into a function that is being called by `f2py`. I have this issue as a placeholder to evaluate the output from this python version vs the original fortran.

**Comment by pochedls** [comment]
@doutriaux1 + @durack1 + @taylor13 

The mkhurrell1.f code would take some time to rewrite in Python, because it is fairly complicated. While most of the mkhurrell.f _functionality_ can be encapsulated in a few lines as a linear algebra solver, most of the _lines of code_ deal with special / weird cases in which the simple solution does non-physical things. 

@durack1 - the compile script + f2py compiles and creates an interface to the fortran code, which is then called in the simple wrapper example I sent you.

**Comment by pochedls** [comment]
@doutriaux1 + @durack1 + @taylor13

One other issue in case there is desire to fix this. This code is in fortran77, which required hardcoding the time series length. This could be problematic if someone wanted to "diddle" a really long time series. It might be possible to make the time series length allocatable, by updating the code to fortran 90 or re-writing it.

**Comment by taylor13** [comment]
Another thing to consider: the fortran code performs a number of useful diagnostics on the data, which, for example, estimate the underestimation of variability that occurs if you simply interpolate the monthly mean values (rather than mid-point values).  Do we want a new code with that capability?

**Comment by durack1** [comment]
To get things working today, I had to follow the notes in https://github.com/CDAT/cd77/issues/4#issuecomment-511505613

**Comment by taylor13** [comment]
@pochedls, @durack1, and I have now successfully extracted guts (the relevant fortran coding) and packaged them with a python driver that is responsible for the I/O.  In addition to the newly written python code, notable changes to the fortran were:

1. making the local arrays (length = length of monthly time series) allocatable, rather than hard-wired.
2.  improving the diagnostics if the solver is unable to converge
3.  Removing some unneeded code (see https://github.com/PCMDI/amipbcs/issues/16 )

Left to do: annotate the code with better documentation.
